server:
  port: 0

spring:
  application:
    name: order-service
  ###############################
  #       DB connection         #
  ###############################
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecc
    username: ecc
    password: ecc1234!
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:42580/eureka

logging:
  level:
    com.example.orderservice: DEBUG