server:
  port: 42590

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # ??? server-url default url set
    service-url:
      defaultZone: http://127.0.0.1:42580/eureka